export { default as Header } from './components/Header/Header';
export { default as Chip } from './components/Chip/Chip';
export { default as Button } from './components/Button/Button';
export { default as Stack } from './components/Stack';
export { StyledText, StyledView } from './components/StyledComponents';
export { default as UserInput } from './components/UserInput/UserInput';
export { default as NativeProvider } from './components/Provider/NativeProvider';
export { horizontalScale, moderateScale, moderateVerticalScale, verticalScale } from './helpers/ResponsiveCalculations';
export { default as Grid } from './components/Grid/Grid';
export { default as Progress } from './components/Progress/Progress';
export { default as Slider } from './components/Slider/Slider';
export { default as Surface } from './components/Surface/Surface';
export { default as Switch } from './components/Switch/Switch';
// export { default as TouchableRipple } from './components/TouchableRipple/TouchableRipple';
export { Dialog, DialogHead, DialogBody, DialogFoot, DialogDescription } from './components/Dialog';
export { default as CheckBox } from './components/CheckBox/CheckBox';
export { default as Avatar } from './components/Avatar';
export { default as Divider } from './components/Divider/Divider';
export { Menu, MenuItem, MenuItemLabel } from './components/Menu';
export { default as IconButton } from './components/IconButton/IconButton';
export { default as Icon } from './components/Icon/Icon';
export { default as PortalProvider } from './components/Portal/PortalProvider';
export { default as Link } from './components/Link/Link';

export { default as LightTheme } from './themes/LightTheme';
export { default as DarkTheme } from './themes/DarkTheme';
// export { default as createTheme } from './themes/createTheme';
export { useColorScheme, useTheme } from './hooks';


export type { HeaderProps } from './components/Header/Header';
export type { ChipProps } from './components/Chip/Chip';
export type { ButtonProps } from './components/Button/Button';
export type { HStackProps } from './components/Stack';
export type { VStackProps } from './components/Stack';
export type { StyledTextProps, StyledViewProps } from './components/StyledComponents';
export type { UserInputProps } from './components/UserInput/UserInput';
export type { ProviderProps } from './components/Provider/NativeProvider';
export type { GridProps } from './components/Grid/Grid';
export type { ProgressProps } from './components/Progress/Progress';
export type { SliderProps } from './components/Slider/Slider';
export type { SurfaceProps } from './components/Surface/Surface';
export type { SwitchProps } from './components/Switch/Switch';
// export type { TouchableRippleProps } from './components/TouchableRipple/TouchableRipple';
export type { DialogProps, DialogHeadProps, DialogBodyProps, DialogFootProps, DialogDescriptionProps } from './components/Dialog';
export type { CheckBoxProps } from './components/CheckBox/CheckBox';
export type { AvatarTextProps, AvatarImageProps } from './components/Avatar';
export type { DividerProps } from './components/Divider/Divider';
export type { MenuProps, MenuItemProps, MenuItemLabelProps } from './components/Menu';
export type { IconButtonProps } from './components/IconButton/IconButton';
export type { IconProps } from './components/Icon/Icon';
// export type { PortalProviderProps } from './components/Portal/PortalProvider';
